### PR TITLE
Update xtensa_imx8ulp.tar.gz overlay tarball

### PR DESCRIPTION
**Pull request by TangleZ**
Generate xtensa_imx8ulp.tar.gz from hifi4 configration package RG2017.
Previous overlay can't build firmware successful.

Signed-off-by: Zhang Peng <peng.zhang_8@nxp.com>

### CODE REVIEW

**Comment by lgirdwood** [comment]
@dbaluta please merge if you are good.

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@lgirdwood all good. Can you please grant me write access to this repo so I can merge?

**Comment by lgirdwood** [comment]
@dbaluta done. Btw, when do you think we can upgrade default GCC (and the default branch )?

**Comment by dbaluta** [comment]
@lgirdwood we are targeting end of this week. @paulstelian97 will be in charge.

**Comment by paulstelian97** [comment]
> @dbaluta done. Btw, when do you think we can upgrade default GCC (and the default branch )?

@lgirdwood Should be good on our end (lightly tested, doesn't seem to introduce any special issues)

**Comment by dbaluta** [comment]
@lgirdwood we are ready to deprecate gcc8.1. gcc10x works fine.

**Comment by dbaluta** [comment]
@TangleZ can you also update GCC for imx8ulp for gcc10x?

**Pull request merged**
